import { PlannerAgent } from './planner-agent.js';
import { TaskOptimizerAgent } from './task-optimizer-agent.js';
import { ExamAgent } from './exam-agent.js';
import { LifeSchedulerAgent } from './life-scheduler-agent.js';
import { handleMcpToolCall, db } from '../mcp-server.js';

// Instantiate the agents
const planner = new PlannerAgent();
const optimizer = new TaskOptimizerAgent();
const exam = new ExamAgent();
const life = new LifeSchedulerAgent();

/**
 * Runs the ADK Multi-Agent Orchestration Flow
 * @param {string} userGoal - The goal entered by the user.
 * @returns {Promise<object>} - Execution trace and structured final result.
 */
export async function runOrchestrator(userGoal) {
  const executionTrace = [];

  const logTrace = (agent, action, message) => {
    executionTrace.push({
      timestamp: new Date().toISOString(),
      agent,
      action,
      message
    });
    console.log(`[Trace] [${agent}] [${action}] ${message}`);
  };

  logTrace('Orchestrator', 'START', `Starting multi-agent resolution for goal: "${userGoal}"`);

  // 1. Planner Agent
  logTrace('Planner Agent', 'PLANNING', 'Analyzing user goal, deconstructing tasks, and designing roadmap...');
  const planResult = await planner.execute(userGoal);
  logTrace('Planner Agent', 'COMPLETE', planResult.summary);

  // Synchronize Tasks to MCP Database
  logTrace('Orchestrator', 'MCP_SYNC', `Registering ${planResult.tasks.length} tasks via MCP tool 'add_task'...`);
  for (const task of planResult.tasks) {
    try {
      handleMcpToolCall('add_task', {
        title: task.title,
        priority: task.priority,
        category: task.category
      });
      logTrace('Orchestrator', 'MCP_TOOL_OK', `Created task: "${task.title}"`);
    } catch (e) {
      logTrace('Orchestrator', 'MCP_TOOL_ERROR', `Failed adding task: "${task.title}". Reason: ${e.message}`);
    }
  }

  // 2. Task Optimization Agent
  logTrace('Task Optimization Agent', 'OPTIMIZATION', 'Prioritizing new tasks and calculating security importance scores...');
  const optimizerResult = await optimizer.execute(userGoal, { tasks: db.tasks });
  logTrace('Task Optimization Agent', 'COMPLETE', optimizerResult.summary);

  // 3. Exam / Study Agent
  logTrace('Exam & Study Agent', 'STUDY_PLAN', `Requesting active study card generation for topic: "${planResult.topic}"...`);
  
  // MCP connector helper to let agent run tools safely
  const mcpConnector = {
    callTool: async (name, args) => {
      logTrace('Exam & Study Agent', 'MCP_CALL', `Calling tool: ${name} with params ${JSON.stringify(args)}`);
      return handleMcpToolCall(name, args);
    }
  };

  const examResult = await exam.execute(userGoal, {
    topic: planResult.topic,
    mcpConnector
  });
  logTrace('Exam & Study Agent', 'COMPLETE', examResult.summary);

  // 4. Life Scheduler Agent
  logTrace('Life Scheduler Agent', 'LIFE_BALANCE', 'Analyzing overall workload density and work-life balance scores...');
  const lifeResult = await life.execute(userGoal, {
    calendar: db.calendar,
    tasks: db.tasks
  });
  logTrace('Life Scheduler Agent', 'COMPLETE', lifeResult.summary);

  // Life Scheduler triggers schedule optimization via MCP
  logTrace('Life Scheduler Agent', 'MCP_CALL', 'Triggering task scheduler optimization via MCP tool...');
  try {
    handleMcpToolCall('optimize_schedule', { factor: 'balanced' });
    logTrace('Orchestrator', 'MCP_TOOL_OK', 'Successfully optimized schedule grid.');
  } catch (e) {
    logTrace('Orchestrator', 'MCP_TOOL_ERROR', `Optimization tool failed: ${e.message}`);
  }

  // Generate Final Collation Output
  const finalOutput = `
<h3>System Resolution Complete!</h3>
<p>Here is your personalized, secure study and lifestyle plan generated by our ADK multi-agent network:</p>

<h4>1. Study & Task Roadmap</h4>
<ul>
  ${planResult.masterPlan.map(p => `<li><strong>${p.day}</strong>: ${p.focus}</li>`).join('')}
</ul>

<h4>2. Optimized Eisenhower Priority Matrix</h4>
<ul>
  ${optimizerResult.optimizedTasks.slice(0, 4).map(t => `<li><code>[${t.quadrant}]</code> ${t.title} (Priority: ${t.priority}, Score: ${t.score})</li>`).join('')}
</ul>

<h4>3. Active Recall Revision Flashcards</h4>
<div class="flashcard-sample-box">
  ${examResult.flashcards.map((f, i) => `
    <div class="sample-card">
      <p class="question"><strong>Q${i+1}:</strong> ${f.question}</p>
      <p class="answer"><strong>A:</strong> ${f.answer}</p>
    </div>
  `).join('')}
</div>

<h4>4. Health & Well-being Audit</h4>
<p><strong>Work-Life Balance:</strong> Study/Work tasks consume ${lifeResult.workPercent}% of your active schedule, leaving ${lifeResult.wellnessPercent}% for wellness and active rest.</p>
<p><strong>Health Rating:</strong> <span class="badge ${lifeResult.healthRating.includes('Warning') ? 'badge-warning' : 'badge-safe'}">${lifeResult.healthRating}</span></p>
<p><strong>Wellness Recommendations:</strong></p>
<ul>
  ${lifeResult.lifeRecommendations.map(r => `<li>At <strong>${r.time}</strong>: ${r.activity}</li>`).join('')}
</ul>
<p><em>Advisor Note: ${lifeResult.advice}</em></p>
  `;

  logTrace('Orchestrator', 'FINISH', 'Multi-agent coordination successfully completed. Final report generated.');

  return {
    finalOutput,
    executionTrace
  };
}
